volumes:
  data:
  config:

services:
  caddy:
    image: caddy:2.8
    restart: always
    command: caddy run --config /etc/caddy/config.json --resume
    cap_add:
      - NET_ADMIN
    environment: 
      CADDY_ADMIN: "0.0.0.0:2019"
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - data:/data
      - config:/config
      - ./config.json:/etc/caddy/config.json
